spring:
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gcp:
      spanner:
        instance-id: petclinic
        database: petclinic
server:
  servlet:
    context-path: /api/visit
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
